server:
  port: 18082
spring:
  application:
    name: oms-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.77.128
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.77.128
    virtual-host: /gmall
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 4
    publisher-confirm-type: correlated
    publisher-returns: true
mybatis-plus:
  mapper-locations: classpath*:mapper/oms/**.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true
ribbon:
  ConnectTimeout: 100000 #连接建立的超时时长，默认1秒
  ReadTimeout: 100000 #处理请求的超时时间，默认为1秒

