server:
  port: 8888
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route # 营销管理路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
#不能写一起，写在一个里是and关系
#            - Path=/search/**
        - id: index-route # 营销管理路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com
        - id: index-route1 # 营销管理路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
