server:
  port: 18081
spring:
  rabbitmq:
    host: 192.168.77.128
    virtual-host: /gmall
    username: admin
    password: admin
    #生产者确认模式
    publisher-confirm-type: correlated
    #开启消息没有到达队列的回调
    publisher-returns: true
  application:
    name: pms-service
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.77.128
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/pms/**.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true
ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

