server:
  port: 18085
spring:
  application:
    name: wms-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.77.128
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true

